module.exports = {
	32cardsDeck: [
		{value: '7',color: 'H'},
		{value: '8',color: 'H'},
		{value: '9',color: 'H'},
		{value: '10',color: 'H'},
		{value: 'J',color: 'H'},
		{value: 'Q',color: 'H'},
		{value: 'K',color: 'H'},
		{value: 'A',color: 'H'},
		{value: '7',color: 'D'},
		{value: '8',color: 'D'},
		{value: '9',color: 'D'},
		{value: '10',color: 'D'},
		{value: 'J',color: 'D'},
		{value: 'Q',color: 'D'},
		{value: 'K',color: 'D'},
		{value: 'A',color: 'D'},
		{value: '7',color: 'S'},
		{value: '8',color: 'S'},
		{value: '9',color: 'S'},
		{value: '10',color: 'S'},
		{value: 'J',color: 'S'},
		{value: 'Q',color: 'S'},
		{value: 'K',color: 'S'},
		{value: 'A',color: 'S'},
		{value: '7',color: 'C'},
		{value: '8',color: 'C'},
		{value: '9',color: 'C'},
		{value: '10',color: 'C'},
		{value: 'J',color: 'C'},
		{value: 'Q',color: 'C'},
		{value: 'K',color: 'C'},
		{value: 'A',color: 'C'}
	]
};